print("Hello shipper")
print("Bảng Cửu Chương 1")
print("1x1=1")
print("1x2=2")
print("...")
print("1x9=9")
print("1x10=10")
print("Không có gì...")
print("Có gì rồi nè...")
print("Thấy không vậy...")